/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Language = "ID" | "EN";

export const translations = {
  ID: {
    // Header & Login
    title: "SISTEM TIKET GOSPLASH",
    subtitle: "Dasbor Penjualan & Pendapatan Waterpark",
    user: "Pengguna",
    logout: "Keluar",
    login_title: "Masuk Sistem GoSplash",
    login_subtitle: "Silakan pilih peran dan masukkan kata sandi Anda untuk melanjutkan.",
    role_label: "Pilih Peran (Role)",
    password_label: "Kata Sandi (Password)",
    password_placeholder: "Masukkan password...",
    login_btn: "MASUK SEKARANG",
    wrong_password: "Password salah! Silakan coba lagi.",
    today_total_revenue: "Pendapatan Hari Ini",
    today_total_transactions: "Transaksi Hari Ini",
    today_total_visitors: "Pengunjung Hari Ini",

    // Cashier Panel
    cashier_title: "Input Transaksi Tiket GoSplash",
    day_tarif: "Hari Tarif:",
    auto_detect: "Otomatis (Deteksi)",
    weekday: "Weekday (Senin-Jumat)",
    weekend: "Weekend (Sabtu-Minggu)",
    unit_price: "Harga Tiket Satuan (Otomatis)",
    system_locked: "Sistem Terkunci",
    num_visitors: "Jumlah Pengunjung (Orang)",
    visitors_placeholder: "Contoh: 3",
    visitor_unit: "Orang",
    select_discount: "Pilih Promo / Diskon Pendukung",
    sewa_loker: "Sewa Loker",
    sewa_tempat: "Sewa Tempat / Saung",
    no_rent: "Tidak Sewa",
    total_to_pay: "Total yang Harus Dibayar",
    breakdown: "Rincian",
    saved: "Hemat",
    payment_method: "Metode Pembayaran",
    cash: "Tunai (Cash)",
    qris: "QRIS Scan",
    card: "EDC Kartu",
    cash_received: "Masukkan Nominal Uang Diterima (Rp)",
    change_due: "Uang Kembalian",
    cash_short: "Uang Kurang!",
    scan_qris_title: "Pindai QRIS GoSplash",
    qris_helper: "Tunjukkan Kode QRIS di atas kepada pengunjung.",
    waiting_payment: "Menunggu Pembayaran (Otomatis)...",
    card_edc_data: "Data Pembayaran Kartu EDC",
    edc_machine: "Mesin EDC",
    ref_no: "No. Reff / Approval",
    edc_helper: "Pastikan transaksi kartu sukses di mesin EDC fisik sebelum menyimpan transaksi.",
    reset: "Reset",
    save_print: "SIMPAN & CETAK NOTA FISIK",
    invalid_visitors: "Masukkan jumlah pengunjung yang valid!",
    insufficient_funds: "Uang pembayaran tidak mencukupi!",

    // Admin Panel
    locked_title: "Dasbor Analisis & Administrasi",
    locked_desc: "Bagian ini dilindungi kata sandi. Hanya Admin yang dapat memodifikasi konfigurasi harga, diskon, dan ekspor/impor data.",
    sales_overview: "Rangkuman Penjualan Hari Ini",
    total_earnings: "TOTAL PENDAPATAN",
    total_tickets: "TIKET TERJUAL",
    total_loker: "SEWA LOKER",
    total_tempat: "SEWA TEMPAT",
    chart_title: "Grafik Pendapatan & Kunjungan",
    period: "Periode Laporan",
    daily: "Harian",
    weekly: "Mingguan",
    monthly: "Bulanan",
    revenue: "Pendapatan (Rp)",
    visitors: "Pengunjung (Orang)",
    search_placeholder: "Cari ID tiket, metode pembayaran, atau diskon...",
    no_tx_found: "Belum ada transaksi terekam untuk kata kunci ini.",
    tx_list: "Daftar Transaksi Tiket Terkini",
    ticket_id: "ID Tiket",
    date: "Tanggal",
    details: "Rincian Tiket & Sewa",
    total: "Total",
    method: "Metode",
    actions: "Aksi",
    receipt_btn: "Nota",
    delete_tx: "Hapus Transaksi",
    reset_all_tx: "HAPUS SEMUA TRANSAKSI & RESET DATA",
    confirm_reset_all: "Apakah Anda yakin ingin menghapus seluruh data transaksi dari penyimpanan lokal?",
    
    // Config Panel
    config_title: "Konfigurasi Tarif & Operasional",
    edit_price: "Ubah Harga Tiket Masuk",
    edit_rental: "Ubah Harga Sewa Loker & Saung",
    loker_tarif_1: "Sewa Loker (Tarif 1)",
    loker_tarif_2: "Sewa Loker (Tarif 2)",
    tempat_tarif_1: "Sewa Saung (Tarif 1)",
    tempat_tarif_2: "Sewa Saung (Tarif 2)",
    save_config: "SIMPAN KONFIGURASI",
    manage_discounts: "Kelola Promo & Diskon Pendukung",
    promo_name: "Nama Promo / Diskon",
    promo_percentage: "Persentase (%)",
    add_promo: "TAMBAH PROMO BARU",
    
    // Backup & Password Manager
    backup_title: "Ekspor & Impor Data (Backup)",
    backup_desc: "Cadangkan atau pulihkan data transaksi dan konfigurasi",
    backup_helper: "Fitur ini membantu Anda mengekspor seluruh transaksi, konfigurasi harga tiket, harga sewa, dan daftar promo aktif ke sebuah file backup (.json) lokal. Anda dapat mengimpor file tersebut di kemudian hari untuk memulihkan seluruh data operasional GoSplash Anda.",
    export_btn: "EKSPOR CADANGAN",
    import_btn: "IMPOR & PULIHKAN",
    security_title: "Keamanan & Password Akses",
    security_desc: "Ubah kata sandi untuk masuk sebagai Admin atau Kasir",
    choose_role: "Pilih Peran (Role)",
    new_password: "Password Baru",
    new_password_placeholder: "Min. 4 karakter",
    confirm_password: "Konfirmasi Password",
    confirm_password_placeholder: "Masukkan ulang...",
    change_password_btn: "UBAH PASSWORD",
    password_empty_err: "Password baru tidak boleh kosong!",
    password_mismatch_err: "Password baru dan konfirmasi tidak cocok!",
    password_changed_success: "Kata sandi berhasil diubah!",

    // Toast Messages
    backup_export_success: "Cadangan data (backup) berhasil diekspor!",
    backup_export_fail: "Gagal mengekspor data cadangan.",
    backup_restore_success: "Data berhasil dipulihkan (restore) dari cadangan!",
    backup_restore_fail: "Gagal memulihkan file cadangan. Format file tidak valid.",
    config_saved_success: "Konfigurasi operasional berhasil disimpan!",

    // Receipts
    receipt_header: "NOTA PEMBAYARAN",
    receipt_eod_header: "LAPORAN END OF DAY (EOD)",
    receipt_eod_desc: "RINGKASAN OPERASIONAL:",
    receipt_eod_income: "RINCIAN PENDAPATAN:",
    receipt_eod_pm: "METODE PEMBAYARAN:",
    print_thermal: "CETAK STRUK FISIK (THERMAL)",
    close: "TUTUP NOTA"
  },
  EN: {
    // Header & Login
    title: "GOSPLASH TICKETING SYSTEM",
    subtitle: "Waterpark Sales & Revenue Dashboard",
    user: "User",
    logout: "Log Out",
    login_title: "Login to GoSplash",
    login_subtitle: "Please select your role and enter your password to continue.",
    role_label: "Select Role",
    password_label: "Password",
    password_placeholder: "Enter password...",
    login_btn: "LOGIN NOW",
    wrong_password: "Incorrect password! Please try again.",
    today_total_revenue: "Today's Revenue",
    today_total_transactions: "Today's Transactions",
    today_total_visitors: "Today's Visitors",

    // Cashier Panel
    cashier_title: "GoSplash Ticket Transaction Input",
    day_tarif: "Tariff Day:",
    auto_detect: "Auto-detect",
    weekday: "Weekday (Mon-Fri)",
    weekend: "Weekend (Sat-Sun)",
    unit_price: "Unit Ticket Price (Auto)",
    system_locked: "System Locked",
    num_visitors: "Number of Visitors (Pax)",
    visitors_placeholder: "Example: 3",
    visitor_unit: "Pax",
    select_discount: "Select Promo / Applicable Discount",
    sewa_loker: "Locker Rental",
    sewa_tempat: "Cottage / Saung Rental",
    no_rent: "No Rental",
    total_to_pay: "Total Amount Due",
    breakdown: "Breakdown",
    saved: "Saved",
    payment_method: "Payment Method",
    cash: "Tunai (Cash)",
    qris: "QRIS Scan",
    card: "EDC Card",
    cash_received: "Enter Cash Amount Received (Rp)",
    change_due: "Change Due",
    cash_short: "Insufficient Cash!",
    scan_qris_title: "Scan GoSplash QRIS",
    qris_helper: "Show the QRIS Code above to the visitor.",
    waiting_payment: "Waiting for Payment (Automated)...",
    card_edc_data: "EDC Card Payment Details",
    edc_machine: "EDC Machine",
    ref_no: "Ref / Approval No.",
    edc_helper: "Ensure the card transaction is successful on physical EDC before saving.",
    reset: "Reset",
    save_print: "SAVE & PRINT PHYSICAL RECEIPT",
    invalid_visitors: "Please enter a valid visitor count!",
    insufficient_funds: "Insufficient payment amount!",

    // Admin Panel
    locked_title: "Analysis & Administration Dashboard",
    locked_desc: "This section is password protected. Only Admin can modify pricing, discounts, and perform data export/import.",
    sales_overview: "Today's Sales Summary",
    total_earnings: "TOTAL INCOME",
    total_tickets: "TICKETS SOLD",
    total_loker: "LOCKER RENTALS",
    total_tempat: "SAUNG RENTALS",
    chart_title: "Revenue & Visitor Charts",
    period: "Report Period",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    revenue: "Revenue (Rp)",
    visitors: "Visitors (Pax)",
    search_placeholder: "Search ticket ID, payment method, or discount...",
    no_tx_found: "No transactions recorded matching this keyword.",
    tx_list: "Recent Ticket Transactions",
    ticket_id: "Ticket ID",
    date: "Date",
    details: "Ticket & Rental Details",
    total: "Total",
    method: "Method",
    actions: "Actions",
    receipt_btn: "Receipt",
    delete_tx: "Delete Transaction",
    reset_all_tx: "DELETE ALL TRANSACTIONS & RESET DATA",
    confirm_reset_all: "Are you sure you want to delete all transaction data from local storage?",

    // Config Panel
    config_title: "Tariff & Operational Configuration",
    edit_price: "Edit Admission Ticket Pricing",
    edit_rental: "Edit Locker & Saung Rental Pricing",
    loker_tarif_1: "Locker Rental (Tariff 1)",
    loker_tarif_2: "Locker Rental (Tariff 2)",
    tempat_tarif_1: "Saung Rental (Tariff 1)",
    tempat_tarif_2: "Saung Rental (Tariff 2)",
    save_config: "SAVE CONFIGURATION",
    manage_discounts: "Manage Promos & Applicable Discounts",
    promo_name: "Promo / Discount Name",
    promo_percentage: "Percentage (%)",
    add_promo: "ADD NEW PROMO",

    // Backup & Password Manager
    backup_title: "Export & Import Data (Backup)",
    backup_desc: "Back up or restore transaction and configuration data",
    backup_helper: "This feature allows you to export all transactions, ticket pricing configs, rental prices, and active promos to a local backup file (.json). You can import this file later to restore all your GoSplash operations.",
    export_btn: "EXPORT BACKUP",
    import_btn: "IMPORT & RESTORE",
    security_title: "Security & Password Access",
    security_desc: "Change password to access as Admin or Cashier",
    choose_role: "Select Role",
    new_password: "New Password",
    new_password_placeholder: "Min. 4 characters",
    confirm_password: "Confirm Password",
    confirm_password_placeholder: "Re-enter...",
    change_password_btn: "CHANGE PASSWORD",
    password_empty_err: "New password cannot be empty!",
    password_mismatch_err: "New password and confirmation do not match!",
    password_changed_success: "Password successfully changed!",

    // Toast Messages
    backup_export_success: "Data backup exported successfully!",
    backup_export_fail: "Failed to export data backup.",
    backup_restore_success: "Data successfully restored from backup!",
    backup_restore_fail: "Failed to restore backup file. Invalid format.",
    config_saved_success: "Operational configuration saved successfully!",

    // Receipts
    receipt_header: "PAYMENT RECEIPT",
    receipt_eod_header: "END OF DAY (EOD) REPORT",
    receipt_eod_desc: "OPERATIONAL SUMMARY:",
    receipt_eod_income: "REVENUE BREAKDOWN:",
    receipt_eod_pm: "PAYMENT METHOD:",
    print_thermal: "PRINT PHYSICAL RECEIPT (THERMAL)",
    close: "CLOSE RECEIPT"
  }
};

export function loadLanguage(): Language {
  return (localStorage.getItem("gosplash_language") as Language) || "ID";
}

export function saveLanguage(lang: Language): void {
  localStorage.setItem("gosplash_language", lang);
}
